// <auto-generated />
using System;
using FamilyTreeSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FamilyTreeSystem.Migrations
{
    [DbContext(typeof(FamilyTreeContext))]
    [Migration("20260111114044_UpdateZiweiColumnNames")]
    partial class UpdateZiweiColumnNames
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("AncestralHallFamilyMember", b =>
                {
                    b.Property<int>("AncestralHallsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FamilyMembersId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AncestralHallsId", "FamilyMembersId");

                    b.HasIndex("FamilyMembersId");

                    b.ToTable("AncestralHallFamilyMember");
                });

            modelBuilder.Entity("FamilyTreeSystem.Models.AncestralHall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("BuiltDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ClanId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClanId");

                    b.HasIndex("UserId");

                    b.ToTable("AncestralHalls");
                });

            modelBuilder.Entity("FamilyTreeSystem.Models.ChildRelation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChildId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RelationshipType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChildId");

                    b.HasIndex("ParentId");

                    b.ToTable("ChildRelations");
                });

            modelBuilder.Entity("FamilyTreeSystem.Models.Clan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AncestorBirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("AncestorName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClanSurname")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("HallName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalAddress")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Clans");
                });

            modelBuilder.Entity("FamilyTreeSystem.Models.ClanActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ActivityDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ClanActivities");
                });

            modelBuilder.Entity("FamilyTreeSystem.Models.FamilyMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BirthOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CertificateAddress")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ClanId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("EducationLevel")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("FamilyMemberId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FatherId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FormerName")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Generation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GraduateSchool")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("IDCardNumber")
                        .HasMaxLength(18)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAlive")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("MeritContribution")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("MotherId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SpouseId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SpouseRelationType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorkUnit")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ZiweiId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClanId");

                    b.HasIndex("FamilyMemberId");

                    b.HasIndex("FatherId");

                    b.HasIndex("MotherId");

                    b.HasIndex("SpouseId");

                    b.HasIndex("UserId");

                    b.HasIndex("ZiweiId");

                    b.ToTable("FamilyMembers");
                });

            modelBuilder.Entity("FamilyTreeSystem.Models.FamilyRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Creator")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("FamilyRules");
                });

            modelBuilder.Entity("FamilyTreeSystem.Models.Grave", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("BurialDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Coordinates")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("MemberId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MemberId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Graves");
                });

            modelBuilder.Entity("FamilyTreeSystem.Models.MigrationRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("FromLocation")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("MemberId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("MigrationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToLocation")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("UserId");

                    b.ToTable("MigrationRecords");
                });

            modelBuilder.Entity("FamilyTreeSystem.Models.SiblingRelation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Member1Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Member2Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RelationshipType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Member1Id");

                    b.HasIndex("Member2Id");

                    b.ToTable("SiblingRelations");
                });

            modelBuilder.Entity("FamilyTreeSystem.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EmailVerifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("RememberToken")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FamilyTreeSystem.Models.Ziwei", b =>
                {
                    b.Property<int>("ZiweiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("Generation")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ZiweiChar")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.HasKey("ZiweiId");

                    b.HasIndex("UserId");

                    b.ToTable("Ziwei");
                });

            modelBuilder.Entity("AncestralHallFamilyMember", b =>
                {
                    b.HasOne("FamilyTreeSystem.Models.AncestralHall", null)
                        .WithMany()
                        .HasForeignKey("AncestralHallsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamilyTreeSystem.Models.FamilyMember", null)
                        .WithMany()
                        .HasForeignKey("FamilyMembersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FamilyTreeSystem.Models.AncestralHall", b =>
                {
                    b.HasOne("FamilyTreeSystem.Models.Clan", "Clan")
                        .WithMany("AncestralHalls")
                        .HasForeignKey("ClanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FamilyTreeSystem.Models.User", "User")
                        .WithMany("AncestralHalls")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FamilyTreeSystem.Models.ChildRelation", b =>
                {
                    b.HasOne("FamilyTreeSystem.Models.FamilyMember", "Child")
                        .WithMany()
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamilyTreeSystem.Models.FamilyMember", "Parent")
                        .WithMany("ChildRelations")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("FamilyTreeSystem.Models.Clan", b =>
                {
                    b.HasOne("FamilyTreeSystem.Models.User", "User")
                        .WithMany("Clans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FamilyTreeSystem.Models.ClanActivity", b =>
                {
                    b.HasOne("FamilyTreeSystem.Models.User", "User")
                        .WithMany("ClanActivities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FamilyTreeSystem.Models.FamilyMember", b =>
                {
                    b.HasOne("FamilyTreeSystem.Models.Clan", "Clan")
                        .WithMany("FamilyMembers")
                        .HasForeignKey("ClanId");

                    b.HasOne("FamilyTreeSystem.Models.FamilyMember", null)
                        .WithMany("Children")
                        .HasForeignKey("FamilyMemberId");

                    b.HasOne("FamilyTreeSystem.Models.FamilyMember", "Father")
                        .WithMany()
                        .HasForeignKey("FatherId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FamilyTreeSystem.Models.FamilyMember", "Mother")
                        .WithMany()
                        .HasForeignKey("MotherId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FamilyTreeSystem.Models.FamilyMember", "Spouse")
                        .WithMany()
                        .HasForeignKey("SpouseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FamilyTreeSystem.Models.User", "User")
                        .WithMany("FamilyMembers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamilyTreeSystem.Models.Ziwei", "Ziwei")
                        .WithMany("FamilyMembers")
                        .HasForeignKey("ZiweiId");

                    b.Navigation("Clan");

                    b.Navigation("Father");

                    b.Navigation("Mother");

                    b.Navigation("Spouse");

                    b.Navigation("User");

                    b.Navigation("Ziwei");
                });

            modelBuilder.Entity("FamilyTreeSystem.Models.FamilyRule", b =>
                {
                    b.HasOne("FamilyTreeSystem.Models.User", "User")
                        .WithMany("FamilyRules")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FamilyTreeSystem.Models.Grave", b =>
                {
                    b.HasOne("FamilyTreeSystem.Models.FamilyMember", "FamilyMember")
                        .WithOne("Grave")
                        .HasForeignKey("FamilyTreeSystem.Models.Grave", "MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamilyTreeSystem.Models.User", "User")
                        .WithMany("Graves")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FamilyMember");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FamilyTreeSystem.Models.MigrationRecord", b =>
                {
                    b.HasOne("FamilyTreeSystem.Models.FamilyMember", "FamilyMember")
                        .WithMany("MigrationRecords")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamilyTreeSystem.Models.User", "User")
                        .WithMany("MigrationRecords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FamilyMember");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FamilyTreeSystem.Models.SiblingRelation", b =>
                {
                    b.HasOne("FamilyTreeSystem.Models.FamilyMember", "Member1")
                        .WithMany("SiblingRelations1")
                        .HasForeignKey("Member1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamilyTreeSystem.Models.FamilyMember", "Member2")
                        .WithMany("SiblingRelations2")
                        .HasForeignKey("Member2Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member1");

                    b.Navigation("Member2");
                });

            modelBuilder.Entity("FamilyTreeSystem.Models.Ziwei", b =>
                {
                    b.HasOne("FamilyTreeSystem.Models.User", "User")
                        .WithMany("Ziwei")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FamilyTreeSystem.Models.Clan", b =>
                {
                    b.Navigation("AncestralHalls");

                    b.Navigation("FamilyMembers");
                });

            modelBuilder.Entity("FamilyTreeSystem.Models.FamilyMember", b =>
                {
                    b.Navigation("ChildRelations");

                    b.Navigation("Children");

                    b.Navigation("Grave");

                    b.Navigation("MigrationRecords");

                    b.Navigation("SiblingRelations1");

                    b.Navigation("SiblingRelations2");
                });

            modelBuilder.Entity("FamilyTreeSystem.Models.User", b =>
                {
                    b.Navigation("AncestralHalls");

                    b.Navigation("ClanActivities");

                    b.Navigation("Clans");

                    b.Navigation("FamilyMembers");

                    b.Navigation("FamilyRules");

                    b.Navigation("Graves");

                    b.Navigation("MigrationRecords");

                    b.Navigation("Ziwei");
                });

            modelBuilder.Entity("FamilyTreeSystem.Models.Ziwei", b =>
                {
                    b.Navigation("FamilyMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
